### ISSUE TITLE
Add time to date property

### ISSUE THREAD

**Issue by SykoraLukas** [inovatika-cz/aplikator#2]

**Comment by vlahoda** [comment]
Stavajici implementace funguje tak, ze se musi nastavit format pattern, ktery obsahuje datumovou a casovou cast oddelenou mezerou, napriklad setFormatPattern("dd.mm.yyyy hh.ii"), ale musi se to nastavit na property. pokud neni nastaven format na property nebo pokud obsahuje jen datumovou cast, do databaze se uklada datum s vynulovanym casem. Format jenom s casem, bez datumu, zatim nefunguje vubec. doplnim...

**Comment by vlahoda** [comment]
Fixed in 77f65eba. 
Pokud format obsahuje pouze cas, zobrazi se pouze timepicker. Pokud obsahuje pouze datum, zobrazuje se pouze datepicker. Pokud oboji, zobrazi se kombinovany datetime picker. 
Zpusob zobrazovani je mozno predefinovat na urovni form widgetu. Format pattern na urovni property urcuje, jestli se do databaze uklada timestamp nebo jen datum s nulovym casem - pokud format obsahuje casovy udaj, uklada se vzdy i cas (nezavisle na pripadnem predefinovani formatu na urovni form widgetu)
